/* Generated By:JavaCC: Do not edit this line. CLLSjTokenManager.java */
import java.util.*;
import java.io.*;
import java.util.logging.*;
import java.util.concurrent.*;

/** Token Manager. */
public class CLLSjTokenManager implements CLLSjConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40L) != 0L || (active1 & 0x800000000000L) != 0L)
            return 0;
         if ((active0 & 0x100000000200L) != 0L || (active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 103;
            return 48;
         }
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 103;
            return 36;
         }
         if ((active0 & 0x40840018000000L) != 0L)
         {
            jjmatchedKind = 103;
            return 25;
         }
         if ((active0 & 0x2800004000000000L) != 0L || (active1 & 0x40205L) != 0L)
         {
            jjmatchedKind = 103;
            return 11;
         }
         if ((active0 & 0x8280008800000000L) != 0L || (active1 & 0x1840134002L) != 0L)
         {
            jjmatchedKind = 103;
            return 21;
         }
         if ((active0 & 0x1440004000L) != 0L || (active1 & 0x20000040L) != 0L)
         {
            jjmatchedKind = 103;
            return 32;
         }
         if ((active0 & 0x553f6202a7ff3c00L) != 0L || (active1 & 0x278fe8bdb8L) != 0L)
         {
            jjmatchedKind = 103;
            return 41;
         }
         return -1;
      case 1:
         if ((active0 & 0xffe766e09bfb1800L) != 0L || (active1 & 0x3fffbbfdbfL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 41;
         }
         if ((active0 & 0x18000224042400L) != 0L || (active1 & 0x400040L) != 0L)
            return 41;
         if ((active0 & 0x800000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 24;
         }
         if ((active0 & 0x100000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 54;
         }
         if ((active1 & 0x40200L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 10;
         }
         if ((active0 & 0x800000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 20;
         }
         if ((active0 & 0x1440004000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 31;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 1;
            }
            return 52;
         }
         return -1;
      case 2:
         if ((active0 & 0xa45400065800L) != 0L || (active1 & 0x3900800080L) != 0L)
            return 41;
         if ((active0 & 0x200L) != 0L)
            return 51;
         if ((active0 & 0xffef42a2fbf90000L) != 0L || (active1 & 0x6ff3fff3fL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 2;
            }
            return 41;
         }
         if ((active0 & 0x800000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 2;
            }
            return 19;
         }
         if ((active0 & 0x100000000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 2;
            }
            return 41;
         }
         return -1;
      case 3:
         if ((active0 & 0x63429420101000L) != 0L || (active1 & 0x102f282720L) != 0L)
            return 41;
         if ((active0 & 0x800000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 32;
               jjmatchedPos = 3;
            }
            return 41;
         }
         if ((active0 & 0xff8c0022dbe90000L) != 0L || (active1 & 0x6d017d81fL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 3;
            }
            return 41;
         }
         return -1;
      case 4:
         if ((active0 & 0x5504003ac3a00000L) != 0L || (active1 & 0xc0048018L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 4;
            }
            return 41;
         }
         if ((active0 & 0xaa88000018490000L) != 0L || (active1 & 0x610135807L) != 0L)
            return 41;
         return -1;
      case 5:
         if ((active0 & 0x7704001840200000L) != 0L || (active1 & 0x40078008L) != 0L)
            return 41;
         if ((active0 & 0x2293800000L) != 0L || (active1 & 0x80000010L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 103;
               jjmatchedPos = 5;
            }
            return 41;
         }
         return -1;
      case 6:
         if ((active0 & 0x4400002291800000L) != 0L)
            return 41;
         if ((active0 & 0x2000000L) != 0L || (active1 & 0x80000010L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 6;
            return 41;
         }
         return -1;
      case 7:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 7;
            return 41;
         }
         if ((active1 & 0x80000010L) != 0L)
            return 41;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 114;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x1L);
      case 40:
         return jjStopAtPos(0, 117);
      case 41:
         return jjStopAtPos(0, 118);
      case 42:
         return jjStopAtPos(0, 110);
      case 43:
         return jjStopAtPos(0, 108);
      case 44:
         return jjStopAtPos(0, 131);
      case 45:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000000L, 0x0L);
      case 46:
         return jjStopAtPos(0, 113);
      case 47:
         jjmatchedKind = 111;
         return jjMoveStringLiteralDfa1_0(0x40L, 0x0L, 0x0L);
      case 58:
         return jjStopAtPos(0, 132);
      case 59:
         jjmatchedKind = 130;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20L);
      case 60:
         jjmatchedKind = 124;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200040000000000L, 0x0L);
      case 61:
         jjmatchedKind = 127;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4400000000000000L, 0x0L);
      case 62:
         jjmatchedKind = 125;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000000000L, 0x0L);
      case 63:
         jjmatchedKind = 115;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000000000L, 0x0L);
      case 94:
         return jjStopAtPos(0, 129);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800008L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1008000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x7600082a90000L, 0x480201430L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000800L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x100000000200L, 0x10000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x224042000L, 0x0L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x5500000001521800L, 0x100L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2100000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x18000000000000L, 0x400000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x40840018000000L, 0x0L, 0x0L);
      case 113:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x1440004000L, 0x20000040L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x8280008800000000L, 0x1840134002L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20020000000400L, 0x20a000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x2800004000000000L, 0x40205L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2080L, 0x0L);
      case 123:
         return jjStopAtPos(0, 119);
      case 124:
         return jjStopAtPos(0, 105);
      case 125:
         return jjStopAtPos(0, 120);
      case 126:
         return jjStopAtPos(0, 112);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(1, 6);
         break;
      case 45:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 106);
         break;
      case 59:
         if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(1, 133);
         break;
      case 61:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 121);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 123);
         else if ((active1 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 126);
         else if ((active2 & 0x1L) != 0L)
            return jjStopAtPos(1, 128);
         break;
      case 62:
         if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         else if ((active1 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 122);
         break;
      case 63:
         if ((active1 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 116);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2820000000000L, active1, 0x1831202000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      case 100:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(1, 70, 41);
         break;
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1c40025800L, active1, 0x420L, active2, 0L);
      case 102:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(1, 26, 41);
         else if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L, active1, 0x8L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000L, active1, 0x2034000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000100000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0x4101000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L, active2, 0L);
      case 110:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x220040000L, active1, 0x840200L, active2, 0L);
      case 111:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(1, 10, 41);
         return jjMoveStringLiteralDfa2_0(active0, 0x8002a90200L, active1, 0x2480008110L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L, active1, 0L, active2, 0L);
      case 114:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 86, 41);
         return jjMoveStringLiteralDfa2_0(active0, 0x40000018000000L, active1, 0x208000080L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x2d00004001000000L, active1, 0x5L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x8280000000000000L, active1, 0x40000002L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x5000240000000000L, active1, 0x100080000L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000L, active1, 0L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0xaa81000000000000L, active1, 0x200034017L);
      case 99:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1600000000L, active1, 0x100L);
      case 100:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 87, 41);
         else if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 101, 41);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 38, 41);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2100000L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000020000000L, active1, 0x40008L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x18080000L, active1, 0x82000L);
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x82a00000L, active1, 0x10200620L);
      case 109:
         if ((active1 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0x1400000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x800100000L, active1, 0x21000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x44000000400000L, active1, 0x1000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000040000000L, active1, 0x800L);
      case 114:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 51);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 47, 41);
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L, active1, 0x40008000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x5002002000000000L, active1, 0x84000000L);
      case 116:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(2, 18, 41);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 42, 41);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 45, 41);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 71, 41);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(2, 96, 41);
         return jjMoveStringLiteralDfa3_0(active0, 0x500000001021000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L, active1, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 33:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(3, 17);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(3, 44);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x5500000000000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L, active1, 0L);
      case 99:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 41);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 54, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L, active1, 0x200000000L);
      case 100:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 93, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L, active1, 0L);
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 41);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 41, 41);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 49, 41);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 53, 41);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 90, 41);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 91, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000040010000L, active1, 0x100000L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10L);
      case 103:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 88, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x2800000000000000L, active1, 0x5L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000200000L, active1, 0x8L);
      case 107:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 41);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 73, 41);
         break;
      case 108:
         if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 85, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L, active1, 0x400L);
      case 110:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 89, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x18080000L, active1, 0L);
      case 111:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L, active1, 0x40000L);
      case 114:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 48, 41);
         else if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 100, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L, active1, 0x3c000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L, active1, 0x10001000L);
      case 116:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 41);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 46, 41);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 77, 41);
         else if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 83, 41);
         return jjMoveStringLiteralDfa4_0(active0, 0x8280000080000000L, active1, 0x80000802L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x440000000L);
      case 118:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 33:
         if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(4, 74);
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2040000000L, active1, 0L);
      case 99:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 41);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L, active1, 0x40000000L);
      case 101:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 76, 41);
         else if ((active1 & 0x4000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 92, 41);
         else if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 97, 41);
         return jjMoveStringLiteralDfa5_0(active0, 0xa200000000000000L, active1, 0x30007L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x5000000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L, active1, 0L);
      case 108:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 22, 41);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L, active1, 0x8L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L, active1, 0x8000L);
      case 112:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 84, 41);
         break;
      case 114:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 41);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000000L);
      case 116:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 19, 41);
         else if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 98, 41);
         return jjMoveStringLiteralDfa5_0(active0, 0x500001812000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L, active1, 0L);
      case 121:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 75, 41);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 33:
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x6L);
      case 76:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 80, 41);
         break;
      case 82:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 81, 41);
         break;
      case 100:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 82, 41);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L, active1, 0L);
      case 101:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 41);
         else if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(5, 67, 41);
         return jjMoveStringLiteralDfa6_0(active0, 0x4400000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10L);
      case 108:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 57, 41);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 41);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x2002000000L, active1, 0L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 21, 41);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 41);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 94, 41);
         break;
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80000000L);
      case 119:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 79, 41);
         break;
      case 121:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(5, 35, 41);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 36, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x80000000L);
      case 100:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 41);
         break;
      case 101:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 41);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 41);
         break;
      case 103:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 24, 41);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L, active1, 0L);
      case 108:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 23, 41);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 58, 41);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 62, 41);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(6, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(6, 66);
         break;
      case 110:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 28, 41);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(7, 68, 41);
         break;
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L, active1, 0L);
      case 116:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 95, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 103:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(8, 25, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 54;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 51:
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(42);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(44, 45);
                  else if (curChar == 35)
                     jjCheckNAdd(39);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 0:
                  if (curChar != 47)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 38:
                  if (curChar == 35)
                     jjCheckNAdd(39);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjCheckNAdd(39);
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 104)
                     kind = 104;
                  jjCheckNAdd(42);
                  break;
               case 43:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(44, 45);
                  break;
               case 44:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(44, 45);
                  break;
               case 45:
                  if (curChar == 34 && kind > 134)
                     kind = 134;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 51:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 48:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 52;
                  else if (curChar == 119)
                     jjCheckNAdd(47);
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 102)
                     jjAddStates(0, 1);
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 21;
                  else if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 54:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 100)
                  {
                     if (kind > 43)
                        kind = 43;
                  }
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 36:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 52:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 32:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 25:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 19:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 100)
                  {
                     if (kind > 32)
                        kind = 32;
                  }
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 10:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 24:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 103)
                        kind = 103;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 99 && kind > 15)
                     kind = 15;
                  break;
               case 4:
               case 13:
                  if (curChar == 101)
                     jjCheckNAdd(3);
                  break;
               case 5:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 12:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 22:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 114 && kind > 32)
                     kind = 32;
                  break;
               case 26:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 101 && kind > 40)
                     kind = 40;
                  break;
               case 28:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 33:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 112 && kind > 40)
                     kind = 40;
                  break;
               case 35:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 37:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 39:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 40:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(41);
                  break;
               case 44:
                  jjAddStates(2, 3);
                  break;
               case 46:
                  if (curChar == 102)
                     jjAddStates(0, 1);
                  break;
               case 47:
                  if (curChar == 100 && kind > 43)
                     kind = 43;
                  break;
               case 49:
                  if (curChar == 114)
                     jjCheckNAdd(47);
                  break;
               case 50:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 53:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 44:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(2, 3);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 54 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x80L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   48, 53, 44, 45, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, "\146\157\162", 
"\164\157", "\154\145\164", "\154\145\164\143", "\151\156", "\162\145\143", null, 
"\143\157\162\145\143", "\154\145\164\41", "\151\156\164", "\143\157\151\156\164", "\154\151\156\164", 
"\143\157\154\151\156\164", "\154\142\157\157\154", "\143\157\154\142\157\157\154", 
"\154\163\164\162\151\156\147", "\143\157\154\163\164\162\151\156\147", "\151\146", "\160\162\151\156\164", 
"\160\162\151\156\164\154\156", "\151\156\146\157", "\162\145\160\145\141\164", 
"\143\154\154\164\171\160\145", null, "\151\156\143\154\165\144\145", "\162\145\143\166", 
"\163\145\156\144\164\171", "\162\145\143\166\164\171", "\144\151\163\143\141\162\144", "\165\163\145", 
"\163\157\155\145", null, "\164\141\153\145", "\160\165\164", null, "\146\167\144\41", 
"\143\165\164", "\143\143\165\164", "\160\141\162", "\143\160\141\162", "\143\141\163\145", 
"\143\150\157\151\143\145", "\157\146\146\145\162", "\157\146", "\164\171\160\145", "\160\162\157\143", 
"\163\164\141\164\145", "\154\163\164\141\164\145", "\163\164\141\164\145\154", 
"\154\163\164\141\164\145\154", "\165\163\141\147\145", "\154\165\163\141\147\145", 
"\165\163\141\147\145\154", "\154\165\163\141\147\145\154", "\163\164\141\164\145\41", 
"\165\163\141\147\145\41", "\163\164\141\164\145\41\154", "\165\163\141\147\145\41\154", 
"\141\146\146\151\156\145", "\143\157\141\146\146\151\156\145", "\143\145\154\154", "\162\144", 
"\167\162\164", "\154\157\143\153", "\165\156\154\153", "\143\145\154\154\41", 
"\145\155\160\164\171", "\143\154\157\163\145", "\167\141\151\164", "\163\150\141\162\145", 
"\142\157\162\162\157\167", "\163\150\141\162\145\114", "\163\150\141\162\145\122", 
"\165\156\146\157\154\144", "\161\165\151\164", "\163\154\145\145\160", "\143\141\154\154", "\157\162", 
"\141\156\144", "\142\141\156\147", "\164\150\145\156", "\145\154\163\145", 
"\164\162\165\145", "\146\141\154\163\145", "\162\141\156\144", "\163\164\162\165\143\164", 
"\143\157\163\164\162\165\143\164", "\155\165\164", "\164\162\141\143\145", "\143\157\155\165\164", 
"\163\141\155", "\163\141\155\162", "\155\157\144", null, null, null, "\174", "\74\55", 
"\55\76", "\53", "\55", "\52", "\57", "\176", "\56", "\41", "\77", "\77\77", "\50", 
"\51", "\173", "\175", "\74\75", "\75\76", "\76\75", "\74", "\76", "\75\75", "\75", 
"\41\75", "\136", "\73", "\54", "\72", "\73\73", null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "ML_COM_NEXT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffffe01L, 0xffffffffffffffffL, 0x7fL, 
};
static final long[] jjtoSkip = {
   0x1feL, 0x0L, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[54];
private final int[] jjstateSet = new int[108];
protected char curChar;
/** Constructor. */
public CLLSjTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public CLLSjTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 54; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 8)
       {
          jjmatchedKind = 8;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
